[package]
name = "app"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
core = { path = "../core" }

actix-web = "4"
serde_json = "1"
uuid = { version = "1.10.0", features = ["v4"] }
