[package]
name = "core"
version = "0.1.0"
license.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
uuid = { version = "1", features = ["v4"] }
